name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:

      fail-fast: false

      matrix:

        shard: [1/2, 2/2]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Allure reports
      run: |
          npm install -D allure-commandline
          npx allure generate ./allure-results --clean

    - name: Run Playwright test
      uses: coactions/setup-xvfb@v1
      with:
          run: npx playwright test --shard ${{ matrix.shard }}
          continue-on-error: true

    - uses: actions/upload-artifact@v3
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ github.run_id }}-${{ github.job }}
        path: playwright-report/
        retention-days: 1
    - uses: actions/upload-artifact@v3
      if: always()
      with:
          name: allure-report-${{ github.run_id }}-${{ github.job }}
          path: allure-report/
          retention-days: 1
    - uses: actions/upload-artifact@v3
      if: always()
      with:
          name: blob-report-${{ github.run_id }}-${{ github.job }}
          path: blob-report/
          retention-days: 1

  merge-reports:

    # Merge reports after playwright-tests, even if some shards have failed

    if: always()

    needs: [test]


    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3

      with:

        node-version: 18

    - name: Install dependencies

      run: npm ci



    - name: Download blob reports from GitHub Actions Artifacts

      uses: actions/download-artifact@v3

      with:

        name: blob-report-${{ github.run_id }}

        path: blob-report/



    - name: Merge into HTML Report

      run: |
          echo '{"testDir": "tests"}' > merge-config.json
          npx playwright merge-reports --reporter html ./blob-report -c merge-config.json



    - name: Upload HTML report

      uses: actions/upload-artifact@v3

      with:

        name: html-report--attempt-${{ github.run_attempt }}

        path: blob-report

        retention-days: 1